spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/db1
    platform: h2
    username: sa
    pas sword:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
server:
  port: 9091